# -*- coding: utf-8 -*-
"""bcc_last_day.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTWlue0hJYNIaP53Y9yc9SWV_KLFkhgM
"""

import sys
def addition(num1, num2): #called function
    print("Addition=", num1+num2)
def substraction(num1, num2):#called function
    print("Substraction=", num1 - num2)
def multiplication(num1, num2):#called function
    print("Multiplication=", num1 * num2)
def division():# called function
    pass  # jab
while True:
    print("1. Addition")
    print("2. Substraction")
    print("3. Multiplication")
    print("4. division ")
    print("5. Exit")
    choice = int(input("Enter your choice from above options :"))
    if choice == 5:
        sys.exit()
    val1   = int(input("Enter First Value :"))
    val2   = int(input("Enter Second Value :"))
    if choice == 1:
        addition(val1, val2)
    elif choice == 2:
        substraction(val1, val2)
    elif choice == 3:
        multiplication(val1, val2)
    elif choice == 4:
        pass
    else:
        print("You have entered wrong choice :")

# nested function
# we will call  outer function first then inner function
def outerFunction():
  print("this is my outer function: ")
  def innerFunction():
    print("this is my inner function: ")
  innerFunction() # would exxceute 3rd
outerFunction()  #execution starts from here

"""A tuple is a basic data structure in Python's official documentation used to store an ordered, immutable collection of items.
Here is what that means in simple terms:
Ordered: The items are stored in a specific sequence, and that order will not change. You can refer to each item using its position (index) within the tuple.
Immutable: Once a tuple is created, you cannot change its contents (add, remove, or modify items). This is the key difference between a tuple and a Python list, which is mutable.
Collection: You can store multiple items in a single tuple. These items can be of different data types (e.g., numbers, strings, or even other tuples).
Tuples are often used to ensure data integrity because their contents cannot be accidentally changed. They are typically created using parentheses () and items are separated by commas.
"""

# input = pratiksha is bad programmer

init_tuple_a = 'a', 'b'
init_tuple_b = ('a', 'b')
print(init_tuple_a == init_tuple_b)
# tuple me parenthesis  mandetory here ()..

init_tuple = ()
print(init_tuple.__len__())
# len length calculate krta since kuch value nhi hai andr 0 dega

init_tuple_a = '1', '2'
init_tuple_b = ('3', '4')
print (init_tuple_a + init_tuple_b)
# parenthesis () ye wla rhega

#hi gpt act as python engineer and explain the prompt
l = [1, 2, 3]
init_tuple = ('Python',) * (l.__len__() - l[::-1][0])
print(init_tuple)

init_tuple =('Python',) * 3
print(type(init_tuple))
# python k baad comma diya to tuple aayega

init_tuple =('Python') * 3
print(type(init_tuple))
# yaha comma nhi diya isliye string class diya

init_tuple =(1,) * 3
init_tuple[0] = 2
print(init_tuple)
# since tuple immutable hai i.e non chnageable
# we already assigned tuple as 1,)() *3
# but then hum tuple ki value chnage krne ki try kr rhe from index 0 as 2
# then error dega wo
# requirement is fixed never changed in future then use tuple if requirement chanaged ho rha hai then use string

init_tuple = ((1, 2),) * 7
print(len(init_tuple[3:8]))
# ((1,2),)*7 creates a tuple with 7 elements.init_tuple[3:8] slices 4 elements → so len(...) = 4.
# tuple contains 7 elements then we slice them from index 3 to 8 where 8 is excluded

# replacing  a string with another string
# s.replace (olstring, newstring)
# inside s, every occurence of oldsretinh will be replaced with new string
s=""
s1=s.replace("dificult","easy")
print(s1)

s="ababababaababaabba"
s1=s.replace("a","b")
print(s1)

# removing spaces from string:
# remove space from:
# rhs ----- rstrip()
# lhs ------lstrip()
# strip() ----- from both sides
city =input("Enter your city name:")
scity = city.strip()
if scity=='Hyderabad':
  print("Hello hydrabadi...adab")
elif scity== 'Chennai':
  print("Hello madrasi....Vannakam")
elif scity =="Banglore":
  print("Hello kannadiga...Shubhodaya")
else:
  print("your entered city is invalid")

# list comprehension
s=[i*i for i in range (1,11)]
# i=1 in range yes 1*1 =1
#i=2 in range yes 2*2 =4
print(s)

# calculatin power using double asteric**
# using list comprehension
val=[2**i for i in range (1,6)]
print(val)

s=[i*i for i in range (1,11)]
# i=1 in range yes 1*1 =1
#i=2 in range yes 2*2 =4
# print(s)

val2 =[i for i in s if i%2==0]
print(val2)

# dictionary comprehension
Sqaures={x:x*x for x in range(1,6)}
print(Sqaures)

doubles={x:2*x for x in range(1,6)}
print(doubles)