# -*- coding: utf-8 -*-
"""BCC_day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk_Clg1B92u7T9VFufBbFWYjs5pflHlb
"""

for i,j in zip(range(1,6), range (5,0,-1)) :
  if i ==3 and j==3:
    continue # sidha next iteration me jayega aage ka statement print nhi krega
  print(i, " ", j)

for i in range(1,6):
  if i==3:
    continue
  print(i, " ", 6-i)

"""while loop:
syntax -> while condition:

we use for loop when we know no of iterations
       while loop when we don't know no. of iterations
"""

i=1
while i<=5:
  print(i)
  i= i+1

"""while loop example: a login page... jab tk correct username and password nhi diya tb tk loop chlta jayega"""

username =' '
password =' '
while username !="admin" and password !="hello":
  username= input("enter username: ")
  password= input("enter password: ")

"""is baaar"""

username =' '
password =' '
while username !="admin" and password !="hello":
  username= input("enter username: ")
  password= input("enter password: ")

n = int(input("Enter a number:")) #n=10
sum=0
i=1 # initialization point i=1
while i<=n:
  sum = sum+i # sum=1
  i=i+1
print("sum of first" ,n, "numbers is:" ,sum)

name="prashant"
newname=" "
# remove duplicate character so that output is prashnt( duplicate a is removed)
for i in name:
    if i not in newname:
        newname += i
print(name)
print(newname)

# write a program to reverse this string using any Loop (for then new variable initialisation)
name ="Prashu"
reverse_var=" "
for i in name:
    reverse_var=i+reverse_var
print(reverse_var)

mycart=[10,20,200,300,800,60,700]
for i in mycart:
  if i>400:
    print("This is my purchased card item")
    continue
  print(i)

# write a program to check if a given string is palindrome
# logic use loops to compare characters from start and end of string
variable="racecar"
for i in variable:
   if variable+1 == variable-1:
    print(i)
# The slice [::-1] means start at the end of the sequence, end at the beginning, and step backward by 1, effectively reversing the sequence.

name="nayan"

if name==name[::-1]:# [start:stop:step]. # In the context of name==name[::-1],
 #[::-1] creates a reversed copy of the name string, which is then compared to the original name to check if it's a palindrome.
    print("palindrome")
else:
    print("not palindrome")

# write a program to check if 2 strings are anagrams of each other
# logic check if the character counts in both strings are same
# output: listen and silent
name="silent"
name_ ="listen"
if sorted (name)== sorted (name_):
  print("anagram")
else:
  print("not anagram")
  # 2 bar sort krege dono naam me

# write a function to add key value pairs to dictionary
# use logic of square brackets or the update() method
mydict={
    "name":"Alice",
    "age":"30",
    "value":30
}


mydict.pop("value") # This would remove the 'value' key and its associated value.
print(mydict)

""" Example of how to add more key-value pairs or use update()
mydict["city"] = "New York"
mydict.update({"occupation": "Engineer", "salary": 70000})
print(mydict)
 The original line 'pop(print(mydict))' was syntactically incorrect for a dictionary definition.
If you meant to remove an item, you would do it after the dictionary is defined:
"""

# write a function to check if a key exists in dictionary
# logic: use in operator or get() method
# output: key exists
mydict={
    "name":"Alice",
    "age":"30",
    "value":30
    }
if "name" in mydict:
  print("key exists")
else:
  print("key does not exist")

"""nested for loop
syntax: 2 loop lagana outer and inner loop
"""

#nested for loop
for i in range(1,4):  # outer loop
  for j in range(1,4):  #inner loop
   print("i", end=" ")

#nested for loop

for i in range(1,4):  # outer loop
  for j in range(1,4):  #inner loop
   print("1", end="02 ")
  print()  # this statement b/c we  want to jump onto next row
  # print("1"....) ye

#nested for loop

for i in range(1,4):  # outer loop
  for j in range(1,4):  #inner loop
   print(i, end="02 ") # is bar i string me nhi hai to a/c to matrix output dega
  print()

n=int(input("Enter the no of rows"))
for i in range(1,n+1):
  for j in range (1, n+1):
    print(chr(64+1), end=" ") # ascii
    print()

n=int(input("Enter the no of rows"))
for i in range(1,n+1):
  for j in range (1, n+2-i):
    print("*", end=" ") #
    print()

n=int(input("Enter the no of rows"))
for i in range(1,n+1):
  for j in range (1, n+1):
    print(n+1-i, end=" 5") # ascii
    print()